version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    volumes:
      - .docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
      args:
        build_env: production
    volumes:
      - .admin_config.php:/var/www/html/.admin_config.php
      - .db_config.php:/var/www/html/.db_config.php
      - .form_config.php:/var/www/html/.form_config.php
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    # phpmyadmin requires that the mysql container be linked as "db"
    links:
      - mysql:db
    depends_on:
      - mysql
    logging:
      driver: none

  mysql:
    image: mysql:5.7
    ports:
      - "33060:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - .docker/mysql/schema.sql:/docker-entrypoint-initdb.d/00-schema.sql
      - .docker/mysql/default.sql:/docker-entrypoint-initdb.d/01-default.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER:?MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS:?MYSQL_PASS}

volumes:
  mysql-volume:
