version: '3'
services:
  web:
    image: "php:5.6-apache"
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    # because the schema isn't defined right
    volumes:
      - mysql-volume:/var/lib/mysql
      - .docker/mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'

volumes:
  mysql-volume:
